# Generated by Django 6.0.6 on 2026-09-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
